admin/jukebox/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^/?$', 'admin.jukebox.views.index'),
    url(r'^source/add/?$', 'admin.jukebox.views.add_source'),
    url(r'^source/(?P<source_id>\d+)/scan/do/?$', 'admin.jukebox.views.do_scan'),
    url(r'^source/(?P<source_id>\d+)/scan/?$', 'admin.jukebox.views.scan_source'),
    url(r'^source/(?P<source_id>\d+)/?$', 'admin.jukebox.views.view_source'),
    url(r'^song/(?P<song_id>\d+)/delete/?$', 'admin.jukebox.views.delete_song'),
    url(r'^song/(?P<song_id>\d+)/edit/?$', 'admin.jukebox.views.edit_song'),
)

admin/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'settings/save/', 'admin.views.save_settings'),
    url(r'settings/', 'admin.views.settings'),
    url(r'users/', include('admin.users.urls')),
    url(r'music/', include('admin.jukebox.urls')),
    url(r'servers/', include('admin.gameservers.urls')),
    url(r'news/', include('admin.news.urls')),
    url(r'tournaments/', include('admin.tournaments.urls')),
    url(r'^/?$', 'admin.views.index'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    url(r'admin/', include('admin.urls')),
    url(r'accounts/', include('accounts.urls')),
    url(r'benchmarks/', include('benchmark.urls')),
    url(r'chat/', include('chat.urls')),
    url(r'gallery/', include('gallery.urls')),
    url(r'music/', include('music.urls')),
    url(r'noms/', include('noms.urls')),
    url(r'servers/', include('servers.urls')),
    url(r'tournaments/', include('tournaments.urls')),
    url(r'notices/?', 'notices.get_notices'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^favicon.ico$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'path': 'favicon.ico'}),
    # always do this, even in production
    url(r'^%s(?P<path>.*)$' % settings.STATIC_URL.lstrip('/'), 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^/?$', 'dashboard.views.index')
)

music/models.py
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User


# Create your models here.
class Request(models.Model):
    song = models.ForeignKey('Music')
    requester = models.ForeignKey(User)
    received_at = models.DateTimeField(auto_now_add=True)
    fulfilled = models.BooleanField(default=False)


class RequestVote(models.Model):
    requester = models.ForeignKey(User)
    request = models.ForeignKey(Request)


class MusicSource(models.Model):
    path = models.CharField(max_length=255)


class Music(models.Model):
    artist = models.CharField(max_length=128)
    album = models.CharField(max_length=128)
    title = models.CharField(max_length=128)
    source = models.ForeignKey(MusicSource)
    filename = models.CharField(max_length=255)
    playing = models.BooleanField(default=False, db_index=True)

    @staticmethod
    def next_song_and_request():
        requests = Request.objects.filter(fulfilled=False)
        requests = requests.annotate(vote_count=Count('requestvote'))
        requests = requests.order_by('-vote_count', 'received_at',)
        if requests.count() != 0:
            return requests[0].song, requests[0]
        else:
            # return a random song
            return Music.objects.order_by('?')[0], None

    @staticmethod
    def currently_playing():
        try:
            return Music.objects.get(playing=True)
        except Music.DoesNotExist:
            return None


    @property
    def associated_request(self):
        try:
            return Request.objects.get(fulfilled=False, song=self)
        except Request.DoesNotExist:
            return None


    def request(self, user):
        # try an active request
        if self.associated_request is None:
            # create a new one
            request = Request()
            request.requester = user
            request.song = self
            request.save()
            vote = RequestVote()
            vote.request = request
            vote.requester = user
            vote.save()
        if self.associated_request.requester != user:
            try:
                RequestVote.objects.get(request=self.associated_request, requester=user)
            except RequestVote.DoesNotExist:
                # good to create it
                vote = RequestVote()
                vote.request = self.associated_request
                vote.requester = user

    @property
    def vote_count(self):
        request = self.associated_request
        if request is None:
            return 0
        return request.requestvote_set.count()

admin/jukebox/forms.py
from django import forms
from music.models import MusicSource
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field
from crispy_forms.bootstrap import FormActions


class NewMusicSourceForm(forms.ModelForm):
    class Meta:
        model = MusicSource

    helper = FormHelper()
    helper.form_enctype = 'multipart/form-data'
    helper.form_action = '/admin/music/source/add'
    helper.layout = Layout(
        Field('path'),
        FormActions(
            Submit('add', 'Add source', css_class="btn-primary"),
        )
    )

admin/jukebox/views.py
from django.db import IntegrityError
from global_decorators import render_to
from admin.decorators import admin_only
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.http import require_POST
from music.models import MusicSource, Music, Request
from admin.jukebox.forms import NewMusicSourceForm
from django.views.decorators.http import condition
from music.scanner import scan_media
from django.utils import simplejson
from os import path


@render_to('music_index.html')
@admin_only
def index(request, form=None):
    sources = MusicSource.objects.all()
    total_music = Music.objects.count()
    total_requests = Request.objects.count()
    outstanding_requests = Request.objects.filter(fulfilled=False).count()
    add_form = form or NewMusicSourceForm()
    icon = "music"
    title = "Music Administration"
    return locals()


@render_to('music_sourcelist.html')
@admin_only
def view_source(request, source_id):
    try:
        source = MusicSource.objects.get(id=source_id)
    except MusicSource.DoesNotExist:
        messages.error(request, "Unable to find the music source with id %s" % source_id)
        return HttpResponseRedirect('/admin/music/')
    icon = "music"
    title = "Music Administration"
    message = "Viewing music from %s" % source.path
    return locals()


@admin_only
@require_POST
def add_source(request):
    add_form = NewMusicSourceForm(data=request.POST)
    if add_form.is_valid() and path.exists(request.POST.get('path')):
        source = add_form.save()
        return HttpResponseRedirect('/admin/music/source/%s/scan/' % source.id)
    else:
        messages.error(request, "Please correct your errors and try again.")
    return index(request, add_form)


@render_to('scan_source.html')
@admin_only
def scan_source(request, source_id):
    icon = "search"
    title = "Scanning for music..."
    try:
        source = MusicSource.objects.get(id=source_id)
    except MusicSource.DoesNotExist:
        messages.error(request, "Unable to find the music source with id %s" % source_id)
        return HttpResponseRedirect('/admin/music/')
    return locals()


@condition(etag_func=None)
@admin_only
def do_scan(request, source_id):
    resp = HttpResponse(scan_media(source_id), content_type='text/html')
    return resp


@admin_only
@require_POST
def delete_song(request, song_id):
    try:
        song = Music.objects.get(id=song_id)
    except Music.DoesNotExist:
        return HttpResponse(simplejson.dumps({"success": False, "error": "Song not found"}), mimetype='application/json')
    song.delete()
    return HttpResponse(simplejson.dumps({"success": True}), mimetype='application/json')


@admin_only
@require_POST
def edit_song(request, song_id):
    try:
        song = Music.objects.get(id=song_id)
    except Music.DoesNotExist:
        return HttpResponse(simplejson.dumps({"success": False, "error": "Song not found"}), mimetype='application/json')
    # update it
    song.artist = request.POST.get('artist') if request.POST.get('artist').__len__() > 0 else song.artist
    song.album = request.POST.get('album') if request.POST.get('album').__len__() > 0 else song.album
    song.title = request.POST.get('title') if request.POST.get('title').__len__() > 0 else song.title
    try:
        song.save()
    except IntegrityError as err:
        return HttpResponse(simplejson.dumps({"success": False, "error": err.message}), mimetype='application/json')
    return HttpResponse(simplejson.dumps({"success": True}), mimetype='application/json')

admin/jukebox/templates/music_index.html
{% extends 'application.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="span7">
        <h2>Music Sources</h2>
        <table id="datatables" class="table table-bordered table-striped responsive">
            <thead>
                <tr>
                    <th>Path</th>
                    <th>Music Files</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
        {% for source in sources %}
                <tr>
                    <td>{{ source.path }}</td>
                    <td>{{ source.music_set.count }}</td>
                    <td class="center">
                        <div class="btn-group">
                            <a href="/admin/music/source/{{ source.id }}/" class="btn btn-info">View</a>
                            <a href="/admin/music/source/{{ source.id }}/scan/" class="btn btn-success">Rescan</a>
                            <a href="/admin/music/source/{{ source.id }}/edit/" class="btn btn-inverse">Edit</a>
                            <a href="/admin/music/source/{{ source.id }}/delete/" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
    </div><!-- /box-body -->
    <div class="span4">
        <div class="well">
            <h4>Add a Source</h4>
            {% crispy add_form %}
        </div>
        <div class="well">
            <h4>Stats</h4>
            <p>Total Music Files: <strong>{{ total_music }}</strong></p>
            <p>Total Requests: <strong>{{ total_requests }}</strong></p>
            <p>Outstanding Requests: <strong>{{ outstanding_requests }}</strong></p>
        </div>
    </div>
    <div class="clearfix"></div>
{% endblock %}

admin/jukebox/templates/music_sourcelist.html
{% extends 'application.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="span11">
        <table id="music_table" class="table datatable table-bordered table-striped responsive" data-edit="/admin/music/song/{0}/edit/">
            <thead>
                <tr>
                    <th>Artist</th>
                    <th>Album</th>
                    <th>Title</th>
                    <th>File Path</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
        {% for music in source.music_set.all %}
                <tr data-id="{{ music.id }}" class="editrow">
                    <td data-field="artist" data-val="{{ music.artist }}">{{ music.artist }}</td>
                    <td data-field="album" data-val="{{ music.album }}">{{ music.album }}</td>
                    <td data-field="title" data-val="{{ music.title }}">{{ music.title }}</td>
                    <td><small>{{ music.filename }}</small></td>
                    <td class="center">
                        <a data-id="{{ music.id }}" href="#" class="confirm-delete btn btn-danger">Delete</a>
                    </td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="clearfix"></div>


    <!-- modal -->
    <div id="confirm-delete-modal" class="modal hide fade">
        <div class="modal-header">
            <a href="#" class="close">&times;</a>
            <h3>Delete the song?</h3>
        </div>
        <div class="modal-body">
            <p>You are about to delete one track from the database, this procedure is irreversible but the song can always
                be added again by rescanning its source.</p>
            <p>Do you want to proceed?</p>
        </div>
        <div class="modal-footer">
            <a href="javascript:confirmedDelete('/admin/music/song/{0}/delete/')" class="btn danger">Yes</a>
            <a href="javascript:$('#confirm-delete-modal').modal('hide')" class="btn secondary">No</a>
        </div>
    </div>
    <!-- /modal -->
{% endblock %}

admin/jukebox/templates/scan_source.html
{% extends 'application.html' %}

{% block content %}
    <div class="box-body">
        <iframe src="/admin/music/source/{{ source.id }}/scan/do/" width="100%" height="400px" frameborder="0"></iframe>
        <div class="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Warning!</strong> Navigating away from this page may interrupt the scan.
        </div>
    </div><!-- /box-body -->
{% endblock %}